import type { Metadata } from "next";
import Script from "next/script";
import AutoRefresh from "./components/AutoRefresh";

export const metadata: Metadata = {
  title: "Production Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en-GB">

      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Production Dashboard</title>

        {/* ✅ Bootstrap */}
        <link href="/bootstrap/bootstrap.min.css" rel="stylesheet" crossOrigin="anonymous" />
        <Script src="/bootstrap/bootstrap.bundle.min.js" crossOrigin="anonymous" strategy="afterInteractive" />

        {/* ✅ Font Awesome icons */}
        <link href="/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />

        {/* ✅ AdminLTE core CSS */}
        <link href="/dist/css/adminlte.min.css" rel="stylesheet" />

        {/* ✅ Global Variables & Animations */}
        <style>
            {`
              @keyframes blink {
                0% { opacity: 1; }
                50% { opacity: 0; }
                100% { opacity: 1; }
              }
            `}
        </style>
      </head>

      <body className="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">
        <AutoRefresh />
        {children}
      </body>
    </html>
  );
}
